name: 网易云日推自动创建歌单
on:
  schedule:
    - cron:  '30 8 * * *'   # 每天 8:30 UTC+8
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 安装网易云 API
      run: |
        git clone https://github.com/shanghaobo/NeteaseCloudMusicApi.git
        cd NeteaseCloudMusicApi && npm install && nohup node app.js &
    - name: 安装备份脚本
      run: git clone https://github.com/shanghaobo/NeteaseCloudMusicDay.git
    - name: 运行脚本
      run: python3 NeteaseCloudMusicDay/main2.py
